"""INPUT=DRAWING CANVAS

OUTPUT=CAN [USE -INDEXING]
OUTPUT=VA N[USE+INDEXING]
OUTPUT=RAW [USE-INDEXING]
OUTPUT=ING   [USE+INDEXING]
"""

i="DRAWING CANVAS"
print(i[-6:-3:1])
print(i[11:6:-2])
print(i[-13:-10:1])
print(i[4:7:1])