"""INPUT=LANGUAGE	

OUTPUT=AGE [USE-INDEXING]
OUTPUT=LANG[USE-INDEXING]
OUTPUT=GUAG [USE-INDEXING]
OUTPUT=NGUA [USE+INDEXING]"""
i="LANGUAGE"
print(i[-3::1])
print(i[-8:-4:1])
print(i[-5:-1:1])
print(i[2:6:1])